#include<stdio.h>
#include<conio.h>
main()
{
	clrscr();
	printf("---------\n");
	printf("|\t|\n");
	printf("k\t|\n");
	printf("r\t|\n");
	printf("i\t|\n");
	printf("s\t|\n");
	printf("h\t|\n");
	printf("|\t|\n");
	printf("---------\n");
	getch();
}
